version: '3'
services:
  workspace:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/task

  serverless:
    build:
      context: .
      target: runtime
    volumes:
      - .:/var/task
    ports:
      - ${APP_PORT}:8080

  neologd-builder:
    build:
      context: .
      target: neologd-builder
