version: '3'
services:
  workspace:
    build:
      context: .
      target: dev
    env_file: .env
    volumes:
      - .:/var/task

  # TODO: rename to RIE
  serverless:
    build:
      context: .
      target: runtime
    env_file: .env
    volumes:
      - .:/var/task
    ports:
      - ${APP_PORT}:8080

  neologd-builder:
    build:
      context: .
      target: neologd-builder
